In [1]:
import pandas as pd

In [4]:
data = ["abhi", "keval", "malhar"]
series = pd.Series(data, index = ['a', 'k', 'm']) #index should match with number in data
print(series)

# print(series.loc['k']) #keval
# print(series.loc['a']) #abhi

# print(series.iloc[2]) # locate using index

series.iloc[1] = 'Solanki'
series.loc['a'] = 'Zala'

print(series)

a      abhi
k     keval
m    malhar
dtype: str
a       Zala
k    Solanki
m     malhar
dtype: str

In [5]:
data = [100,101, 105, 150, 123, 178, 190, 200, 220]
series = pd.Series(data)
# print(series)

# print(series[series >= 140]) # give all value that is bigger than 140
print(series[(series > 140) & (series < 200)]) # give all value that is bigger than 140 and less than 200
# dont use and/or in pandas series and dataframes

3    150
5    178
6    190
dtype: int64

In [6]:
calories = {"Day 1": 1400,
            "Day 2": 1700,
            "Day 3": 1800,
            "Day 4": 1500,
            "Day 5": 2000}

series = pd.Series(calories)
print(series)
print()

# series.loc["Day 3"] += 400

# print(series)

print(series[series >= 2000])

Day 1    1400
Day 2    1700
Day 3    1800
Day 4    1500
Day 5    2000
dtype: int64

Day 5    2000
dtype: int64

DataFrame

In [4]:
pokemons = pd.read_csv('datasets/pokemon.csv', usecols=['attack', 'base_total', 'capture_rate', 'defense', 'height_m', 'hp',
       'name', 'pokedex_number', 'sp_attack', 'sp_defense', 'speed', 'type1',
       'type2', 'weight_kg', 'generation', 'is_legendary'])
pokemons.head()

,attack,base_total,capture_rate,defense,height_m,hp,name,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,49,318,45,49,0.7,45,Bulbasaur,1,65,65,45,grass,poison,6.9,1,0
1,62,405,45,63,1.0,60,Ivysaur,2,80,80,60,grass,poison,13.0,1,0
2,100,625,45,123,2.0,80,Venusaur,3,122,120,80,grass,poison,100.0,1,0
3,52,309,45,43,0.6,39,Charmander,4,60,50,65,fire,NaN,8.5,1,0
4,64,405,45,58,1.1,58,Charmeleon,5,80,65,80,fire,NaN,19.0,1,0

In [ ]:
pokemons.tail()
pokemons.columns
pokemons.shape
pokemons.isnull().sum()
pokemons.name
pokemons[['name', 'attack', 'defense']]
pokemons.type1.unique()
pokemons.type1.value_counts()

,attack,base_total,capture_rate,defense,height_m,hp,name,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
796,101,570,25,103,9.2,97,Celesteela,797,107,101,61,steel,flying,999.9,7,1
797,181,570,255,131,0.3,59,Kartana,798,59,31,109,grass,steel,0.1,7,1
798,101,570,15,53,5.5,223,Guzzlord,799,97,53,43,dark,dragon,888.0,7,1
799,107,600,3,101,2.4,97,Necrozma,800,127,89,79,psychic,NaN,230.0,7,1
800,95,600,3,115,1.0,80,Magearna,801,130,115,65,steel,fairy,80.5,7,1

In [ ]:
pokemons[pokemons.attack > 100]
pokemons[pokemons.defense < 50]
pokemons[ pokemons['is_legendary'] == 1]
pokemons.loc[ pokemons.generation == 1]

In [ ]:
pokemons['type2'].isnull().sum()
pokemons.loc[pokemons.type2.isnull()]
pokemons.loc[pokemons["type2"].isnull(), "name"]
pokemons.type2.fillna("None")
pokemons.height_m.fillna(pokemons.height_m.mean())
pokemons.weight_kg.fillna(pokemons.height_m.median())
pokemons.dropna().isna().sum()

In [ ]:
pokemons.sort_values(by= ["attack"], ascending=True)
pokemons.sort_values(by= ["defense"], ascending=False)
pokemons.sort_values(by = ["speed"], ascending=False)
pokemons.sort_values(by = ["hp"], ascending=False).head()
pokemons.sort_values(by = ['base_total'], ascending=False).iloc[0]
pokemons.sort_values(by=['generation', "attack"])

In [ ]:
pokemons.groupby('type1').attack.mean()
pokemons.groupby('generation').defense.mean()
pokemons.groupby('generation').size()
# or
pokemons["generation"].value_counts().sort_index()
pokemons.groupby('type1').speed.agg(['max'])
pokemons.groupby('type1').hp.agg(['min'])
pokemons.groupby("type1").weight_kg.mean()
pokemons.groupby('generation').is_legendary.sum()
pokemons.groupby('is_legendary').base_total.mean()

In [ ]:
pokemons['power'] = pokemons.attack + pokemons.sp_attack
pokemons['bulk'] = pokemons.defense + pokemons.sp_defense
pokemons['is_fast'] = (pokemons.speed > 100).astype(int)
pokemons['is_heavy'] = (pokemons.weight_kg > 100).astype(int)
pokemons

In [ ]:
pokemons.sort_values(by = ['base_total']).groupby('type1').head(3)
pokemons.sort_values(by=['base_total'], ascending=False).groupby('generation').head(1)
pokemons.loc[pokemons.groupby('type1').attack.idxmax()]
pokemons.groupby('is_legendary')[['attack', 'defense', 'hp', 'speed', 'sp_attack', 'sp_defense']].mean()
pokemons[['attack', 'defense', 'hp', 'speed', 'sp_attack', 'sp_defense']].corr()
pokemons[pokemons.duplicated()]
pd.to_numeric(pokemons.capture_rate, errors= 'coerce')

In [ ]:
pokemons.groupby('type1').attack.mean().idxmax()
pokemons.groupby('is_legendary').speed.mean().idxmax()
pokemons.groupby('generation').base_total.max().sort_values(ascending=False)
pokemons.groupby('generation').base_total.max().idxmax()
pokemons[["weight_kg", "defense"]].corr()
pokemons.groupby("type1").is_legendary.sum().sort_values(ascending=False)
    #   or
pokemons[pokemons["is_legendary"] == 1]["type1"].value_counts()
pokemons.groupby('type1').base_total.mean().idxmax()
pokemons.groupby("type1")["base_total"].mean().sort_values(ascending=False)
pokemons[pokemons.is_legendary == 0].sort_values(by=['base_total'],ascending=False).head(10)

type1
psychic     17
dragon       7
water        6
steel        6
electric     5
fire         5
rock         4
grass        4
normal       3
dark         3
bug          3
ice          2
ground       2
ghost        1
flying       1
fairy        1
Name: count, dtype: int64

In [10]:
pokemons[[
    "attack","defense","speed",
    "hp","sp_attack","sp_defense"
]].corr()

              attack   defense     speed        hp  sp_attack  sp_defense
attack      1.000000  0.468915  0.352703  0.410616   0.368154    0.265836
defense     0.468915  1.000000  0.007934  0.242378   0.241882    0.526348
speed       0.352703  0.007934  1.000000  0.160760   0.438981    0.225977
hp          0.410616  0.242378  0.160760  1.000000   0.365973    0.366971
sp_attack   0.368154  0.241882  0.438981  0.365973   1.000000    0.511496
sp_defense  0.265836  0.526348  0.225977  0.366971   0.511496    1.000000

In [ ]:
pokemons.sort_values('base_total', ascending=False).groupby("generation").head(5)
num_cols = pokemons.select_dtypes(include=["int64", "float64"]).columns

pokemons[num_cols] = (pokemons[num_cols] - pokemons[num_cols].min()) / \
                    (pokemons[num_cols].max() - pokemons[num_cols].min())
pokemons.pivot_table(values="attack", index="type1", aggfunc="mean")